/**
 * Deterministic policy document parsing: text layer, registry, first adapter.
 *
 * NO NETWORK, NO DB, NO MODEL CALL. Every PDF here is SYNTHETIC, generated by
 * fixtures/policyDocs/generate.mjs from template.mjs. Expected values are
 * written out by hand from that template, never taken from the parser.
 * The OCR tests run the real local OCR engine on image-only pages.
 *
 * Run:  npx tsx --test backend/server/tests/policyDocParser.test.ts
 */

import { test, describe, after } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { parsePolicyDocument } from "../services/policyDocs";
import { acquireText, DocumentReadError, LIMITS } from "../services/policyDocs/textLayer";
import { identifyAndParse, register, registeredAdapters, type PolicyAdapter } from "../services/policyDocs/registry";
import { tesseractOcr, shutdownOcr } from "../services/policyDocs/ocr";

const here = path.dirname(fileURLToPath(import.meta.url));
const fx = (f: string) => new Uint8Array(fs.readFileSync(path.join(here, "fixtures/policyDocs", f)));
after(async () => { await shutdownOcr(); });

/** The template's terms, typed out by hand. */
const EXPECTED: Record<string, unknown> = {
  "identity.insurer": "HDFC Life",
  "identity.plan": "Click 2 Achieve",
  "identity.uin": "101N186V02",
  "identity.option": "Dream Achiever",
  "identity.benefit_choice": "Early Income",
  "identity.linked": "non_linked",
  "identity.participating": "non_participating",
  "schedule.currency": "INR",
  "schedule.annualized_premium": { paise: 20000000 },
  "schedule.instalment_premium_first_year": { paise: 20000000 },
  "schedule.instalment_premium_renewal": { paise: 20000000 },
  "schedule.extra_premium": { paise: 0 },
  "schedule.premium_excludes_taxes": true,
  "schedule.policy_term_years": 15,
  "schedule.premium_paying_term_years": 7,
  "schedule.frequency": "annual",
  "schedule.commencement_date": "2024-03-16",
  "schedule.risk_commencement_date": "2024-03-04",
  "schedule.premium_due_day_month": { day: 4, month: 3 },
  "schedule.final_premium_due_date": "2030-03-04",
  "schedule.policy_end_date": "2039-03-04",
  "schedule.grace_days": 30,
  "schedule.sum_assured_on_death": { paise: 200000000 },
  "schedule.deferral_selected": false,
  "schedule.premium_offset_selected": false,
  "benefits.survival_recurring": { amount: { paise: 338000 }, frequency: "monthly", from: "2024-04-04", to: "2039-03-04" },
  "benefits.survival_terminal": { amount: { paise: 140000000 }, date: "2039-03-04" },
  "definitions.policy_anniversary_anchor": "risk_commencement_date",
  "definitions.total_premiums_paid_excludes": ["extra premium", "rider premium", "taxes"],
  "grace.rule": { monthlyDays: 15, otherDays: 30 },
  "surrender.selection": "higher_of_gsv_ssv",
  "surrender.gsv_acquisition_min_premium_years": 2,
  "surrender.ssv_basis": "discounted_outstanding_survival_and_maturity_benefits",
  "surrender.ssv_reference_tenor": { upToTermYears: 20, tenorUpTo: 10, tenorAbove: 30 },
  "surrender.ssv_discount_rule": { base: "annualized_yield_reference_gsec", roundUpBps: 25, roundBeforeSpread: false, spread: { bps: 150 }, reviewDayMonth: [{ day: 25, month: 2 }, { day: 25, month: 8 }] },
  "surrender.ssv_printed_rate": { bps: 925 },
  "discount_rate.general_rule": { base: "annualized_yield_reference_gsec", roundUpBps: 25, roundBeforeSpread: false, spread: { bps: 100 }, reviewDayMonth: [] },
  "status.lapse_without_gsv": "lapsed_cover_ceases_no_benefits",
  "status.lapse_with_gsv": "paid_up",
  "revival.window": { years: 5, from: "due_date_of_first_unpaid_premium", beforeTermExpiry: true },
  "revival.printed_rate": { bps: 950 },
  "revival.rate_rule": { base: "average_annualized_10y_gsec_6_months", roundUpBps: 50, roundBeforeSpread: true, spread: { bps: 200 }, reviewDayMonth: [{ day: 25, month: 2 }, { day: 25, month: 8 }] },
  "loan.cap_pct_of_surrender_value": { bps: 8000 },
  "loan.deduction_before_benefits": true,
  "loan.foreclosure": { appliesTo: "other_than_in_force_and_fully_paid_up", thresholdPctOfSurrenderValue: { bps: 9000 }, comparison: "strictly_greater" },
  "loan.foreclosure_exemption": { statuses: ["in_force", "fully_paid_up"], groundWording: "exceeding_the_surrender_value" },
  "loan.rate_fixed_for_term_clause": true,
  "loan.rate_revised_until_next_revision_clause": true,
  "loan.printed_rate": { bps: 950 },
  "loan.msme_concessions": [{ who: "female", reductionBps: 200 }, { who: "other_than_female", reductionBps: 150 }],
  "options.deferral_available": true,
  "options.premium_offset_available": true,
};

/** Clause and page each group of fields must cite (template page numbers). */
const PAGES: [string, number, string][] = [
  ["identity.uin", 1, "Policy document title"],
  ["schedule.annualized_premium", 1, "Policy Schedule"],
  ["schedule.grace_days", 2, "Policy Schedule"],
  ["benefits.survival_recurring", 2, "Policy Schedule"],
  ["definitions.policy_anniversary_anchor", 3, "Definitions: Policy Anniversary"],
  ["grace.rule", 4, "Part C 3. Payment and cessation of Premiums"],
  ["surrender.gsv_formula", 4, "Part D 1. Surrender Value"],
  ["surrender.gsv_factor_bands", 4, "Part D 1. Surrender Value"],
  ["status.paid_up_formula", 4, "Part D 2. Lapsed Policies and Paid-Up policies"],
  ["revival.window", 4, "Part D 3. Revival of the Policy"],
  ["discount_rate.general_rule", 4, "Part D 4. Discount rate"],
  ["loan.foreclosure", 5, "Part D 8. Loans"],
];

describe("golden synthetic digital document", async () => {
  const r = await parsePolicyDocument(fx("c2a-digital.pdf"));
  const f: any = r.outcome.fields;

  test("is matched to exactly one adapter, with every page read from embedded text", () => {
    assert.equal(r.outcome.status, "supported");
    assert.equal(r.outcome.adapterId, "hdfc-click2achieve-101N186V02-dream-achiever-early-income");
    assert.ok(r.pageMethods.every((p) => p.method === "embedded_text"));
    assert.match(r.sha256, /^[0-9a-f]{64}$/);
  });

  test("every expected field is found with the expected value", () => {
    for (const [k, want] of Object.entries(EXPECTED)) {
      assert.equal(f[k]?.state, "found", `${k}: ${JSON.stringify(f[k])}`);
      assert.deepEqual(f[k].value, want, k);
    }
  });

  test("NA and absent benefits stay explicit; the final survival benefit is not relabelled maturity", () => {
    assert.equal(f["benefits.maturity"].state, "not_applicable");
    assert.equal(f["benefits.income"].state, "not_applicable");
    assert.equal(f["schedule.juvenile_ci_sum_assured"].state, "not_applicable");
    assert.deepEqual(f["benefits.survival_terminal"].value.amount, { paise: 140000000 });
  });

  test("commencement and risk commencement are both kept, and differ", () => {
    assert.notEqual(f["schedule.commencement_date"].value, f["schedule.risk_commencement_date"].value);
  });

  test("the GSV table is read band by band, with the ramp as a formula tree", () => {
    const bands = f["surrender.gsv_factor_bands"].value;
    assert.deepEqual(bands.map((b: any) => [b.from, b.to]), [[2, 2], [3, 3], [4, 7], [8, "term_minus_2"], ["term_minus_1", "term"]]);
    assert.deepEqual(bands[0].factor, { k: "num", n: "3", d: "10" });
    assert.deepEqual(bands[1].factor, { k: "num", n: "7", d: "20" });
    assert.deepEqual(bands[2].factor, { k: "num", n: "1", d: "2" });
    assert.deepEqual(bands[4].factor, { k: "num", n: "9", d: "10" });
    assert.equal(bands[3].factor.k, "add");
  });

  test("every field cites its page, printed page and clause", () => {
    for (const [k, page, clause] of PAGES) {
      assert.equal(f[k].source.pdfPage, page, k);
      assert.equal(f[k].source.printedPage, String(page), k);
      assert.equal(f[k].source.clause, clause, k);
      assert.equal(f[k].source.method, "embedded_text");
      assert.equal(f[k].source.documentSha256, r.sha256);
      assert.ok(f[k].source.region && f[k].source.region.w > 0, k);
    }
  });

  test("no customer identity row is ever read into a field or excerpt", () => {
    const all = JSON.stringify(r.outcome);
    for (const s of ["SYNTHETIC TEST HOLDER", "SYN-POL-4471", "Example Road", "Testville"]) assert.ok(!all.includes(s), s);
  });

  test("raises the review points the wording itself creates", () => {
    const ids = r.outcome.flags.map((x) => x.id).sort();
    assert.deepEqual(ids, [
      "foreclosure_exemption_wording", "gsv_factor_rounding_not_stated", "loan_rate_clauses_conflict",
      "msme_concession_needs_eligibility", "ssv_needs_current_rate", "survival_benefit_deduction_timing",
    ]);
    const blocking = r.outcome.flags.filter((x) => x.blocksCalculation).map((x) => x.id).sort();
    assert.deepEqual(blocking, ["gsv_factor_rounding_not_stated", "loan_rate_clauses_conflict", "ssv_needs_current_rate", "survival_benefit_deduction_timing"]);
  });
});

describe("refusals and conflicts", () => {
  const variant = async (name: string) => (await parsePolicyDocument(fx(`variants/${name}.pdf`))).outcome;

  test("another UIN version is unsupported, not read as V02", async () => {
    const o = await variant("other-version");
    assert.equal(o.status, "unsupported");
    assert.ok(o.reasons.some((x) => x.includes("101N186V03")));
    assert.deepEqual(o.fields, {});
  });
  test("another plan option is unsupported", async () => {
    const o = await variant("other-option");
    assert.equal(o.status, "unsupported");
    assert.ok(o.reasons.some((x) => x.includes("Dream Builder")));
  });
  test("a missing UIN is unsupported", async () => {
    const o = await variant("no-uin");
    assert.equal(o.status, "unsupported");
  });
  test("two different UINs in one file need review", async () => {
    const o = await variant("two-uins");
    assert.equal(o.status, "needs_review");
  });
  test("a schedule value printed twice with different amounts is conflicting, not first-wins", async () => {
    const o: any = await variant("conflicting-premium");
    assert.equal(o.status, "supported");
    assert.equal(o.fields["schedule.annualized_premium"].state, "conflicting");
    assert.equal(o.fields["schedule.annualized_premium"].candidates.length, 2);
  });
  test("a missing GSV table is missing; the rest still reads", async () => {
    const o: any = await variant("truncated-gsv");
    assert.notEqual(o.fields["surrender.gsv_factor_bands"].state, "found");
    assert.equal(o.fields["surrender.gsv_formula"].state, "found");
  });
  test("a changed ramp formula is refused, not interpreted", async () => {
    const o: any = await variant("ramp-altered");
    assert.equal(o.fields["surrender.gsv_factor_bands"].state, "unsupported");
  });
  test("reordered pages still read, and cite the pages where things now are", async () => {
    const o: any = await variant("reordered");
    assert.equal(o.status, "supported");
    assert.equal(o.fields["surrender.gsv_formula"].state, "found");
    assert.equal(o.fields["surrender.gsv_formula"].source.pdfPage, 3);
  });
  test("a schedule with deferral selected says so", async () => {
    const o: any = await variant("deferral-yes");
    assert.equal(o.fields["schedule.deferral_selected"].value, true);
  });
});

describe("text layer limits", () => {
  test("a file that is not a PDF is refused", async () => {
    await assert.rejects(acquireText(new TextEncoder().encode("hello")), (e: any) => e instanceof DocumentReadError && e.code === "not_a_pdf");
  });
  test("a damaged PDF is refused", async () => {
    await assert.rejects(acquireText(new TextEncoder().encode("%PDF-1.4 garbage")), (e: any) => e.code === "corrupt");
  });
  test("an oversized file is refused before parsing", async () => {
    const big = new Uint8Array(LIMITS.maxBytes + 1);
    big.set(new TextEncoder().encode("%PDF-1.4"));
    await assert.rejects(acquireText(big), (e: any) => e.code === "too_large");
  });
  test("an image-only PDF without OCR says OCR is needed, rather than returning nothing", async () => {
    await assert.rejects(acquireText(fx("c2a-scanned.pdf")), (e: any) => e.code === "ocr_unavailable");
  });
});

describe("OCR fallback (real local OCR engine)", () => {
  test("mixed file: only the image page is OCR'd; every value read is right or refused", { timeout: 180000 }, async () => {
    const r = await parsePolicyDocument(fx("c2a-mixed.pdf"), { ocr: tesseractOcr });
    assert.deepEqual(r.pageMethods.map((p) => p.method), ["embedded_text", "embedded_text", "embedded_text", "ocr", "embedded_text"]);
    assert.equal(r.outcome.status, "supported");
    const f: any = r.outcome.fields;
    for (const [k, want] of Object.entries(EXPECTED)) {
      if (f[k]?.state === "found") assert.deepEqual(f[k].value, want, `${k} was read wrongly from OCR`);
    }
    // Schedule pages were digital, so they are all found.
    assert.equal(f["schedule.annualized_premium"].state, "found");
    const ocrFound = Object.values(f).filter((x: any) => x.state === "found" && x.source.method === "ocr");
    if (ocrFound.length) assert.ok(r.outcome.flags.some((x) => x.id === "read_by_ocr"));
  });

  test("scanned file: every page is OCR'd; nothing is read wrongly", { timeout: 300000 }, async () => {
    const r = await parsePolicyDocument(fx("c2a-scanned.pdf"), { ocr: tesseractOcr });
    assert.ok(r.pageMethods.every((p) => p.method === "ocr"));
    const f: any = r.outcome.fields;
    for (const [k, want] of Object.entries(EXPECTED)) {
      if (f[k]?.state === "found") assert.deepEqual(f[k].value, want, `${k} was read wrongly from OCR`);
    }
    if (r.outcome.status === "supported") assert.ok(r.outcome.flags.some((x) => x.id === "read_by_ocr"));
  });
});

describe("registry contract", () => {
  const fake = (id: string, match: boolean): PolicyAdapter => ({
    id, version: "0.0.1", insurer: "Example Life", product: "Example", uin: "999N000V01", supports: "test",
    identify: () => (match ? { result: "match" } : { result: "no_match", reason: `${id} does not match` }),
    parse: () => ({ fields: {}, flags: [] }),
  });
  const docStub: any = { sha256: "x", pageCount: 0, pages: [], extractor: { id: "t", version: "t" }, ocrUsed: false };

  test("a second product registers without touching the orchestrator", () => {
    const before = registeredAdapters().length;
    register(fake("test-second-product", false));
    assert.equal(registeredAdapters().length, before + 1);
  });
  test("the same id cannot register twice", () => {
    assert.throws(() => register(fake("test-second-product", false)));
  });
  test("two matching adapters need review; none is unsupported with each reason", () => {
    assert.equal(identifyAndParse(docStub, [fake("a", true), fake("b", true)]).status, "needs_review");
    const none = identifyAndParse(docStub, [fake("a", false), fake("b", false)]);
    assert.equal(none.status, "unsupported");
    assert.equal(none.reasons.length, 2);
  });
  test("an adapter that throws gives needs_review, not a crash", () => {
    const boom: PolicyAdapter = { ...fake("boom", true), parse: () => { throw new Error("x"); } };
    assert.equal(identifyAndParse(docStub, [boom]).status, "needs_review");
  });
});

describe("no model anywhere in this path", () => {
  test("nothing under services/policyDocs imports the AI service or a model client", () => {
    const dir = path.join(here, "../services/policyDocs");
    const files: string[] = [];
    const walk = (d: string) => { for (const e of fs.readdirSync(d, { withFileTypes: true })) e.isDirectory() ? walk(path.join(d, e.name)) : files.push(path.join(d, e.name)); };
    walk(dir);
    for (const file of files) {
      const src = fs.readFileSync(file, "utf8");
      assert.doesNotMatch(src, /aiService|generative-ai|@google|openai|anthropic|gemini/i, path.basename(file));
      assert.doesNotMatch(src, /\beval\s*\(|new Function\s*\(/, path.basename(file));
    }
  });
});
