import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from "node:url";
// scripts/ops/<this file>  ->  repo root. Resolved from the file, not the
// working directory, so these run correctly from anywhere.
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

import fs from 'fs';
import pkg from 'pg';

dotenv.config({ path: path.resolve(REPO_ROOT, '.env.local') });
dotenv.config({ path: path.resolve(REPO_ROOT, '.env') });
dotenv.config();

const { Pool } = pkg;

// DATABASE_URL carries `?sslmode=require`. Since pg 8.15 that string is honoured and turns on full
// certificate verification, which beats the `ssl` option below and fails against the Supabase
// pooler's self-signed chain ("self-signed certificate in certificate chain") on every single row.
// Strip the parameter so the explicit ssl config is what actually applies: we still connect over
// TLS, we just do not verify the chain, which is the behaviour this script always had.
function connectionString() {
  const raw = process.env.DATABASE_URL;
  if (!raw) return raw;
  try {
    const u = new URL(raw);
    u.searchParams.delete('sslmode');
    return u.toString();
  } catch {
    return raw;
  }
}

const pool = new Pool({
  connectionString: connectionString(),
  ssl: { rejectUnauthorized: false },
});

// catalog_seed stayed under backend/ with the data it seeds.
const SEED_DIR = path.join(REPO_ROOT, 'backend', 'catalog_seed');

const REQUIRED = ['uin', 'insurer', 'plan_name', 'product_type'];

async function run() {
  if (!fs.existsSync(SEED_DIR)) {
    console.error('No catalog_seed/ directory.');
    process.exit(1);
  }
  const files = fs.readdirSync(SEED_DIR).filter((f) => f.endsWith('.json'));
  console.log(`Loading ${files.length} seed file(s) from catalog_seed/…\n`);

  let ok = 0, skipped = 0;
  // Every (uin, variant) this run loaded. Retiring a seed FILE never used to retire its catalogue
  // ROW, so a product collapsed back from three variants to one kept all three live in the
  // database and the collapse looked like it had silently failed. The seed directory is the
  // source of truth: anything active here that no seed describes is stale.
  const loadedUins = [], loadedVariants = [];
  for (const file of files) {
    let seed;
    try {
      seed = JSON.parse(fs.readFileSync(path.join(SEED_DIR, file), 'utf-8'));
    } catch (e) {
      console.error(`  ✗ ${file}: invalid JSON — ${e.message}`);
      skipped++; continue;
    }
    const missing = REQUIRED.filter((k) => !seed[k]);
    if (missing.length) {
      console.error(`  ✗ ${file}: missing ${missing.join(', ')}`);
      skipped++; continue;
    }
    try {
      // variant is '' for a product with no named tiers, which is most of them. The unique key
      // is (uin, variant) since migration 023: Classic and Elite share a UIN and must not
      // overwrite each other. plan_key is generated by the database, never inserted.
      await pool.query(
        `INSERT INTO policy_catalog
           (uin, variant, insurer, plan_name, product_type, sum_insured_options, profile, source_file, status, confidence, updated_at)
         VALUES ($1,$10,$2,$3,$4,$5,$6,$7,$8,$9, NOW())
         ON CONFLICT (uin, variant) DO UPDATE SET
           insurer = EXCLUDED.insurer,
           plan_name = EXCLUDED.plan_name,
           product_type = EXCLUDED.product_type,
           sum_insured_options = EXCLUDED.sum_insured_options,
           profile = EXCLUDED.profile,
           source_file = EXCLUDED.source_file,
           status = EXCLUDED.status,
           confidence = EXCLUDED.confidence,
           updated_at = NOW()`,
        [
          seed.uin, seed.insurer, seed.plan_name, seed.product_type,
          seed.sum_insured_options ?? null, JSON.stringify(seed),
          seed.source_file ?? null, seed.status ?? 'unverified', seed.confidence ?? null,
          typeof seed.variant === 'string' ? seed.variant.trim() : '',
        ]
      );
      console.log(`  ✓ ${seed.insurer} / ${seed.plan_name}  [${seed.uin}]`);
      loadedUins.push(seed.uin);
      loadedVariants.push(typeof seed.variant === 'string' ? seed.variant.trim() : '');
      ok++;
    } catch (e) {
      console.error(`  ✗ ${file}: DB error — ${e.message}`);
      skipped++;
    }
  }

  // Reconcile activation against the seed directory, in this order.
  //
  // First revive anything a seed describes: a row can have been deactivated by the supersede pass
  // below on an earlier run, and if that product has since been collapsed back to a single row it
  // must come back. This is only safe because the two other reasons a row is deactivated are both
  // re-applied every run: the supersede pass runs immediately after this, and the Bajaj regional
  // clones are retired by fix_catalog_names.mjs, which MUST be run after every load anyway.
  const revived = await pool.query(
    `UPDATE policy_catalog p
        SET is_active = true, updated_at = NOW()
       FROM unnest($1::text[], $2::text[]) AS s(uin, variant)
      WHERE p.uin = s.uin AND p.variant = s.variant AND p.is_active = false
      RETURNING p.uin`,
    [loadedUins, loadedVariants],
  );

  // Then retire anything no seed describes any more, which is how a collapsed variant disappears.
  const orphaned = await pool.query(
    `UPDATE policy_catalog p
        SET is_active = false, updated_at = NOW()
      WHERE p.is_active = true
        AND NOT EXISTS (
          SELECT 1 FROM unnest($1::text[], $2::text[]) AS s(uin, variant)
           WHERE s.uin = p.uin AND s.variant = p.variant
        )
      RETURNING p.uin, p.variant`,
    [loadedUins, loadedVariants],
  );
  if (revived.rowCount) console.log(`\nRevived ${revived.rowCount} row(s) that a seed still describes.`);
  if (orphaned.rowCount) {
    console.log(`Retired ${orphaned.rowCount} row(s) with no seed file:`);
    orphaned.rows.slice(0, 12).forEach((r) => console.log(`  ${r.uin}${r.variant ? ` (${r.variant})` : ''}`));
    if (orphaned.rowCount > 12) console.log(`  … and ${orphaned.rowCount - 12} more`);
  }

  // A product that used to be one catalogue row is several once its variants are extracted. The
  // original blank-variant row is not overwritten by them, because the key is (uin, variant) and
  // "Silver" is not "". Left active it would sit alongside its own variants carrying the single
  // ranked value that variants exist to replace, so retire it. Deactivated, never deleted.
  const stale = await pool.query(
    `UPDATE policy_catalog p
        SET is_active = false, updated_at = NOW()
      WHERE p.variant = '' AND p.is_active = true
        AND EXISTS (
          SELECT 1 FROM policy_catalog v
           WHERE v.uin = p.uin AND v.variant <> '' AND v.is_active = true
        )
      RETURNING p.uin`
  );
  if (stale.rowCount) {
    console.log(`\nRetired ${stale.rowCount} variant-less row(s) now superseded by named variants.`);
  }

  const { rows } = await pool.query(
    `SELECT product_type, COUNT(*)::int AS n FROM policy_catalog WHERE is_active GROUP BY product_type ORDER BY n DESC`
  );
  console.log(`\nLoaded ${ok}, skipped ${skipped}. Catalog now holds:`);
  rows.forEach((r) => console.log(`  ${r.product_type}: ${r.n}`));
  process.exit(0);
}

run();
