openapi: 3.0.3
info:
  title: Sach AI Policy Analysis API
  description: |
    Deterministic, replayable, and schema-locked API for forensic insurance policy analysis.
    Enforces strict idempotency, extensive audit trails, and codified error states.
    
    ## 1. Canonical Status Model
    Uses a single lifecycle enum: `uploaded` -> `extracting` -> `wordings_fetch` -> `auditing` -> `transforming` -> `completed` / `failed`.
    
    ## 2. Idempotency
    Analysis is sealed by (PDF Binary SHA256 + Password). Duplicate submissions return existing jobs unless `force_rerun` is set.
    
    ## 3. Audit Trails
    All responses carry `schema_version`, `prompt_hash`, `model_version`, and `policy_wordings_checksum` to ensure forensic defensibility.
  version: 2.0.0
servers:
  - url: http://localhost:5000/api
    description: Production API Server

paths:
  /analyze:
    post:
      summary: Submit a policy document for forensic analysis
      description: |
        Initiates an asynchronous analysis job.
        Strictly idempotent based on file SHA-256 and password.
        Always returns 202 Accepted for new jobs, or 200/202 for existing jobs.
      operationId: submitAnalysis
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [policy]
              properties:
                policy:
                  type: string
                  format: binary
                  description: The policy PDF file. Max 25MB.
                password:
                  type: string
                  description: Optional password for protected PDFs.
                force_rerun:
                  type: boolean
                  default: false
                  description: If true, bypasses idempotency check and forces new analysis.
      responses:
        '202':
          description: Analysis accepted and queued.
          headers:
            Location:
              description: URI to poll for status.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionResponse'
        '200':
          description: Idempotent return of existing job (if force_rerun=false).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionResponse'
        '400':
          description: Invalid input (File too large, wrong type).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - Analysis already exists and re-run not allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /status/{jobId}:
    get:
      summary: Get deterministic status and result of a job
      description: Returns the current status and result (only if completed). Partial results are strictly forbidden.
      operationId: getJobStatus
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Current job status and (if complete) result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatusResponse'
        '404':
          description: Job not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    # 1. Canonical Status Model (LOCKED)
    JobLifecycleStatus:
      type: string
      enum:
        - uploaded
        - extracting
        - wordings_fetch
        - auditing
        - transforming
        - completed
        - failed
      description: Single source of truth for job lifecycle. Matches JobStatus.schema.json.

    # 2. Submission Response
    SubmissionResponse:
      type: object
      required:
        - analysis_id
        - job_id
        - status
        - schema_version
        - received_at
        - policy_file_checksum
      properties:
        analysis_id:
          type: string
          format: uuid
        job_id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/JobLifecycleStatus'
        schema_version:
          type: string
          example: "2.0.0"
        received_at:
          type: string
          format: date-time
        policy_file_checksum:
          type: string
          pattern: "^[a-f0-9]{64}$"

    # 4. Status Response
    JobStatusResponse:
      type: object
      required:
        - analysis_id
        - job_id
        - status
        - current_step
        - progress
        - updated_at
        - schema_version
      properties:
        analysis_id:
          type: string
          format: uuid
        job_id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/JobLifecycleStatus'
        current_step:
          $ref: '#/components/schemas/JobLifecycleStatus'
        progress:
          type: integer
          minimum: 0
          maximum: 100
        updated_at:
          type: string
          format: date-time
        schema_version:
          type: string
          description: "Must be >= 2.0.0"
        
        # 7. Audit Metadata Propagation (Mandatory)
        prompt_hash:
          type: string
          pattern: "^[a-f0-9]{64}$"
        model_version:
          type: string
        policy_wordings_checksum:
          type: string
          pattern: "^[a-f0-9]{64}$"
        
        result:
          $ref: './ForensicAuditReport.schema.json'
          nullable: true
          description: Present ONLY when status=completed.
        
        error:
          $ref: '#/components/schemas/ErrorObject'
          nullable: true
          description: Present ONLY when status=failed.

    # 5. Error Object (Strict)
    ErrorObject:
      type: object
      required:
        - code
        - message
        - failure_stage
        - retryable
      properties:
        code:
          type: string
          enum:
            - OCR_FAILED
            - WORDINGS_NOT_FOUND
            - MODEL_TIMEOUT
            - SCHEMA_VIOLATION
            - IDEMPOTENCY_CONFLICT
            - INTERNAL_ERROR
        message:
          type: string
        failure_stage:
          $ref: '#/components/schemas/JobLifecycleStatus'
        retryable:
          type: boolean
    
    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          $ref: '#/components/schemas/ErrorObject'

    # 6. Limits & Guardrails
    SystemLimits:
      type: object
      description: Enforced system limits. Not returned in API but defined here for contract.
      properties:
        max_file_size_mb:
          type: integer
          const: 25
        max_page_count:
          type: integer
          const: 100
        max_token_budget_per_job:
          type: integer
          const: 1000000
        job_ttl_hours:
          type: integer
          const: 24
        result_retention_days:
          type: integer
          const: 30

    # 8. Versioning Rules
    VersioningPolicy:
      type: object
      properties:
        min_supported_schema_version:
          type: string
          const: "2.0.0"
        version_mismatch_behavior:
          type: string
          enum: ["reject", "warn"]
          const: "reject"
