"""Regenerate client/src/fonts.css and client/src/fonts/*-rupee-*.woff.

Run from frontend/:  python scripts/gen-fonts.py   (needs fontTools)

Why this exists
---------------
The site uses Inter and Playfair Display from @fontsource. Two traps:

1. fontsource's per-subset CSS files (latin-400.css, latin-ext-400.css...)
   have NO unicode-range, so importing latin + latin-ext made every visitor
   download both files for every weight. The full-weight files (400.css) do
   carry the ranges, so this script copies the latin and latin-ext faces out of
   those, ranges intact.

2. Even with the ranges, the only latin-ext character the site actually shows
   is the rupee sign (U+20B9). One glyph would pull a 20-36 KB latin-ext file
   per weight on every page that shows a price. So the rupee gets its own
   ~1.3 KB face per weight (subset from fontsource's own latin-ext file), and
   U+20B9 is cut out of the latin-ext range. latin-ext still loads, as before,
   for a page that shows any other character from it.

Both fonts are SIL Open Font License; subsetting is permitted.
"""

import re
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FACES = [
    ("inter", "300", "normal"),
    ("inter", "400", "normal"),
    ("inter", "500", "normal"),
    ("inter", "600", "normal"),
    ("playfair-display", "400", "normal"),
    ("playfair-display", "400", "italic"),
    ("playfair-display", "500", "normal"),
    ("playfair-display", "600", "normal"),
    ("playfair-display", "700", "normal"),
]
RUPEE = 0x20B9
FAMILY_NAME = {"inter": "Inter", "playfair-display": "Playfair Display"}


def rupee_face(pkg: str, weight: str, style: str) -> str:
    src = ROOT / f"node_modules/@fontsource/{pkg}/files/{pkg}-latin-ext-{weight}-{style}.woff"
    font = TTFont(src)
    if RUPEE not in font.getBestCmap():
        raise SystemExit(f"{src.name} has no rupee sign")
    opts = subset.Options()
    opts.flavor = "woff"
    opts.layout_features = ["*"]
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=[RUPEE])
    sub.subset(font)
    out = ROOT / f"client/src/fonts/{pkg}-rupee-{weight}-{style}.woff"
    out.parent.mkdir(parents=True, exist_ok=True)
    font.save(out)
    return (
        f"/* {pkg}-rupee-{weight}-{style} */\n"
        "@font-face {\n"
        f"  font-family: '{FAMILY_NAME[pkg]}';\n"
        f"  font-style: {style};\n"
        "  font-display: swap;\n"
        f"  font-weight: {weight};\n"
        f"  src: url(./fonts/{out.name}) format('woff');\n"
        "  unicode-range: U+20B9;\n"
        "}"
    )


def subset_blocks(pkg: str, weight: str, style: str) -> list[str]:
    name = weight if style == "normal" else f"{weight}-italic"
    css = (ROOT / f"node_modules/@fontsource/{pkg}/{name}.css").read_text(encoding="utf-8")
    blocks = [
        b.strip()
        for b in re.split(r"(?=/\* )", css)
        if re.match(rf"/\* {pkg}-latin(-ext)?-{weight}-{style} \*/", b)
    ]
    if len(blocks) != 2:
        raise SystemExit(f"{pkg} {name}: expected latin + latin-ext, got {len(blocks)}")
    out = []
    for b in blocks:
        b = b.replace("url(./files/", f"url(../../node_modules/@fontsource/{pkg}/files/")
        if "-latin-ext-" in b:
            # The rupee has its own face above; keep it out of this one.
            if "U+20AD-20C0" not in b:
                raise SystemExit(f"{pkg} {name}: latin-ext range changed, update the split")
            b = b.replace("U+20AD-20C0", "U+20AD-20B8,U+20BA-20C0")
        out.append(b)
    return out


def main() -> None:
    parts = [
        "/* GENERATED by scripts/gen-fonts.py; edit that, not this. Latin and\n"
        "   latin-ext faces of Inter and Playfair Display with their unicode-range,\n"
        "   plus a ~1.3 KB rupee-only face per weight. See the script for why. */"
    ]
    for pkg, weight, style in FACES:
        parts.append(rupee_face(pkg, weight, style))
        parts.extend(subset_blocks(pkg, weight, style))
    (ROOT / "client/src/fonts.css").write_text("\n".join(parts) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote client/src/fonts.css ({len(FACES) * 3} faces)")


if __name__ == "__main__":
    main()
