// Strings for the WhatsApp card, English and Hindi, kept INSIDE this plug-in folder so
// unplugging never means editing the shared locale files.
// Commands in the guide (HELP, SHARE, RENEWALS...) stay English in both languages: they are
// what the bot listens for (whatsapp-bot/src/core/templates.ts help/more).

export const STRINGS = {
  en: {
    title: "WhatsApp",
    beta: "Beta",
    intro: "Send a customer's health policy PDF to the IndSure WhatsApp number and get the report back in the same chat. You can also ask about a report, get a share message for your customer, and see renewals.",
    step: "Step",
    done: "Done",
    save_title: "Save our contact",
    save_body: "Tap the button and press Save. Our chat will then show as IndSure AI Assistant, not a number.",
    save_contact: "Save contact",
    save_skip: "I've already saved it",
    save_again: "Save it again",
    saved_body: "Saved. Our chat shows as IndSure AI Assistant.",
    connect_title: "Connect your number",
    connect_locked: "Save our contact first. This step opens after that.",
    number_label: "Your WhatsApp number",
    number_placeholder: "10-digit mobile number",
    get_code: "Get my code",
    getting_code: "Getting code...",
    send_this: "From this WhatsApp number, send this message to",
    code_expires: "The code works for 10 minutes.",
    open_whatsapp: "Open WhatsApp with this message",
    check_again: "I've sent it, check again",
    connected_as: "Connected:",
    disconnect: "Disconnect",
    disconnecting: "Disconnecting...",
    disconnected: "WhatsApp disconnected.",
    first_title: "Send your first policy",
    first_locked: "Opens once your number is connected.",
    first_body: "Open the chat and send a customer's health policy PDF. The report comes back in about a minute.",
    open_chat: "Open the chat",
    guide_title: "How to use it",
    guide_pdf_title: "Send a policy PDF",
    guide_pdf_body: "Forward the PDF to the chat. Each new policy uses one policy check, same as the portal.",
    guide_ask_title: "Ask about it",
    guide_ask_body: "After the report, type a question like",
    guide_ask_example: "room rent? co-pay?",
    guide_share_title: "Share with your customer",
    guide_share_body: "Type this for a message you can forward:",
    guide_calls_title: "See who to call",
    guide_calls_body: "Type one of these:",
    guide_help_title: "Stuck?",
    guide_help_body: "Type this to see everything it can do:",
    guide_read_more: "Read the full guide",
    never_sends: "IndSure never messages your customers. It only replies to you, and you press send yourself.",
    beta_note: "This is a beta number and it may change. We'll tell you if it does.",
    load_failed: "Couldn't load your WhatsApp connection.",
  },
  hi: {
    title: "WhatsApp",
    beta: "बीटा",
    intro: "ग्राहक की हेल्थ पॉलिसी की PDF, IndSure के WhatsApp नंबर पर भेजें और उसी चैट में रिपोर्ट पाएं। आप रिपोर्ट के बारे में सवाल पूछ सकते हैं, ग्राहक के लिए भेजने लायक मैसेज ले सकते हैं, और रिन्यूअल देख सकते हैं।",
    step: "कदम",
    done: "हो गया",
    save_title: "हमारा कॉन्टैक्ट सेव करें",
    save_body: "बटन दबाइए और Save दबाइए। फिर हमारी चैट नंबर की जगह IndSure AI Assistant नाम से दिखेगी।",
    save_contact: "कॉन्टैक्ट सेव करें",
    save_skip: "मैंने पहले ही सेव कर लिया है",
    save_again: "फिर से सेव करें",
    saved_body: "सेव हो गया। हमारी चैट IndSure AI Assistant नाम से दिखती है।",
    connect_title: "अपना नंबर जोड़ें",
    connect_locked: "पहले हमारा कॉन्टैक्ट सेव करें। उसके बाद यह कदम खुलेगा।",
    number_label: "आपका WhatsApp नंबर",
    number_placeholder: "10 अंकों का मोबाइल नंबर",
    get_code: "मेरा कोड पाएं",
    getting_code: "कोड आ रहा है...",
    send_this: "इसी WhatsApp नंबर से, यह मैसेज यहां भेजें:",
    code_expires: "यह कोड 10 मिनट तक काम करेगा।",
    open_whatsapp: "यह मैसेज WhatsApp में खोलें",
    check_again: "मैंने भेज दिया, फिर से देखें",
    connected_as: "जुड़ा हुआ नंबर:",
    disconnect: "हटाएं",
    disconnecting: "हटा रहे हैं...",
    disconnected: "WhatsApp हटा दिया गया।",
    first_title: "अपनी पहली पॉलिसी भेजें",
    first_locked: "नंबर जुड़ने के बाद यह कदम खुलेगा।",
    first_body: "चैट खोलें और ग्राहक की हेल्थ पॉलिसी की PDF भेजें। रिपोर्ट लगभग एक मिनट में आ जाती है।",
    open_chat: "चैट खोलें",
    guide_title: "इसे कैसे इस्तेमाल करें",
    guide_pdf_title: "पॉलिसी की PDF भेजें",
    guide_pdf_body: "PDF को चैट में फ़ॉरवर्ड करें। हर नई पॉलिसी में एक पॉलिसी चेक लगता है, पोर्टल की तरह।",
    guide_ask_title: "उसके बारे में पूछें",
    guide_ask_body: "रिपोर्ट के बाद ऐसा सवाल लिखें:",
    guide_ask_example: "room rent? co-pay?",
    guide_share_title: "ग्राहक को भेजें",
    guide_share_body: "फ़ॉरवर्ड करने लायक मैसेज के लिए यह लिखें:",
    guide_calls_title: "किसे कॉल करना है",
    guide_calls_body: "इनमें से एक लिखें:",
    guide_help_title: "अटक गए?",
    guide_help_body: "सब कुछ देखने के लिए यह लिखें:",
    guide_read_more: "पूरी गाइड पढ़ें",
    never_sends: "IndSure आपके ग्राहकों को कभी मैसेज नहीं भेजता। वह सिर्फ़ आपको जवाब देता है, और भेजने का बटन आप खुद दबाते हैं।",
    beta_note: "यह बीटा नंबर है और बदल सकता है। बदलने पर हम आपको बताएंगे।",
    load_failed: "आपका WhatsApp कनेक्शन लोड नहीं हो सका।",
  },
} as const

export type WaStringKey = keyof typeof STRINGS.en
